// app/products.js
const products = [
  {
    id: 1,
    name: "Double Sofa",
    image: "https://via.placeholder.com/150",
    price: 200,
    category: "Furniture",
    stock: 3,
    rating: 4.0,
  },
  {
    id: 2,
    name: "Single Sofa",
    image: "https://via.placeholder.com/150",
    price: 150,
    category: "Furniture",
    stock: 3,
    rating: 4.0,
  },
  {
    id: 3,
    name: "Arm Chair",
    image: "https://via.placeholder.com/150",
    price: 100,
    category: "Furniture",
    stock: 3,
    rating: 4.0,
  },
  {
    id: 4,
    name: "Phone Model 01",
    image: "https://via.placeholder.com/150",
    price: 300,
    category: "Electronics",
    stock: 3,
    rating: 4.0,
  },
  {
    id: 5,
    name: "Phone Model 02",
    image: "https://via.placeholder.com/150",
    price: 400,
    category: "Electronics",
    stock: 3,
    rating: 4.0,
  },
  {
    id: 6,
    name: "Wireless Earbuds",
    image: "https://via.placeholder.com/150",
    price: 50,
    category: "Accessories",
    stock: 3,
    rating: 4.0,
  },
  {
    id: 7,
    name: "Smart Watch",
    image: "https://via.placeholder.com/150",
    price: 120,
    category: "Accessories",
    stock: 3,
    rating: 4.0,
  },
  {
    id: 8,
    name: "Gaming Chair",
    image: "https://via.placeholder.com/150",
    price: 250,
    category: "Furniture",
    stock: 3,
    rating: 4.0,
  },
  {
    id: 9,
    name: "Desk Lamp",
    image: "https://via.placeholder.com/150",
    price: 30,
    category: "Accessories",
    stock: 3,
    rating: 4.0,
  },
  {
    id: 10,
    name: "Wireless Keyboard",
    image: "https://via.placeholder.com/150",
    price: 80,
    category: "Electronics",
    stock: 3,
    rating: 4.0,
  },
];

export default products;
